// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";

function str(prim) {
  return prim;
}

var footeStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.background(Css.rgb(244, 244, 244)),
            /* [] */0
          ]),
      /* :: */[
        "footer",
        /* [] */0
      ]
    ]);

var Styles = {
  footeStyles: footeStyles
};

function Footer(Props) {
  return React.createElement("footer", {
              className: "Styles.footerStyles"
            }, React.createElement("div", {
                  className: "content has-text-centered"
                }), React.createElement("p", undefined, React.createElement("strong", undefined, "Brac Fac")), "made with ReasonML and NextJS");
}

var make = Footer;

export {
  str ,
  Styles ,
  make ,
  
}
/* footeStyles Not a pure module */
