// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";

function str(prim) {
  return prim;
}

var heroStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.backgroundImage(Css.url("/static/images/heroBackground.jpg")),
            /* :: */[
              Css.backgroundPosition(Css.pct(50), Css.pct(50)),
              /* :: */[
                Css.backgroundRepeat(Css.noRepeat),
                /* :: */[
                  Css.backgroundSize(Css.cover),
                  /* :: */[
                    Css.color(Css.rgb(242, 242, 2242)),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]),
      /* :: */[
        "hero",
        /* :: */[
          "is-medium",
          /* [] */0
        ]
      ]
    ]);

var titleStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.color(Css.rgb(242, 242, 242)),
            /* [] */0
          ]),
      /* :: */[
        "title",
        /* [] */0
      ]
    ]);

var subTitleStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.color(Css.rgb(242, 242, 242)),
            /* [] */0
          ]),
      /* :: */[
        "subTitle",
        /* [] */0
      ]
    ]);

function Hero(Props) {
  var title = Props.title;
  var subTitle = Props.subTitle;
  return React.createElement("section", {
              className: heroStyles
            }, React.createElement("div", {
                  className: "hero-body"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("h1", {
                          className: "titleStyles"
                        }, title), React.createElement("h2", {
                          className: "subTitleStyles"
                        }, subTitle))));
}

var make = Hero;

export {
  str ,
  heroStyles ,
  titleStyles ,
  subTitleStyles ,
  make ,
  
}
/* heroStyles Not a pure module */
