// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function Post(Props) {
  return React.createElement("div", {
              className: "column is-one-third"
            }, React.createElement("div", {
                  className: "card"
                }, React.createElement("div", {
                      className: "card-content"
                    }, React.createElement("div", {
                          className: "media"
                        }, React.createElement("div", {
                              className: "media-content"
                            }, React.createElement("p", {
                                  className: "title is-four"
                                }, "Post title"), React.createElement("p", {
                                  className: "subtitle is-six"
                                }, "subtitle"))), React.createElement("div", {
                          className: "content"
                        }, "Lorem ipsum dolor sit amet. Consectetur necessitatibus voluptate voluptates cupiditate excepturi repellat, incidunt dolores at culpa recusandae, exercitationem beatae totam, optio aliquam iste quo autem quos laudantium!", React.createElement("a", {
                              href: "#"
                            }, "#css"), React.createElement("a", {
                              href: "#"
                            }, "#responsive"), React.createElement("div", undefined, "11:09 PM - 1 Jan 2019")))));
}

var make = Post;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
