// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Section$ReNext from "../src/components/layout/layout/Section.bs.js";

function str(prim) {
  return prim;
}

function About(Props) {
  return React.createElement(Section$ReNext.make, {
              title: "About",
              subtitle: "This is the about page",
              children: React.createElement("p", undefined, "The light is your friend. Preserve it. Get tough with it, get strong. We'll put some happy little leaves here and there.")
            });
}

var make = About;

var $$default = About;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
