// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Section$ReNext from "../src/components/Page/Section.bs.js";

function str(prim) {
  return prim;
}

function Contact(Props) {
  return React.createElement(Section$ReNext.make, {
              title: "Contact",
              subtitle: "This is the contact page",
              children: React.createElement("p", undefined, "I'm a water fanatic. I love water. Follow the lay of the land. It's most important. No worries. No cares. Just float and wait for the wind to blow you around.")
            });
}

var make = Contact;

var $$default = Contact;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
