// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Section$ReNext from "../src/components/Page/Section.bs.js";

function str(prim) {
  return prim;
}

function Index(Props) {
  return React.createElement(Section$ReNext.make, {
              title: "Bracket Factory",
              subtitle: "Bracket Factory Blog built with ReasonML and NextJS",
              children: null
            }, React.createElement("p", undefined, "A tree needs to be your friend if you're going to paint him. And I know you're saying, 'Oh Bob, you've done it this time.' And you may be right."), React.createElement("p", undefined, "You need the dark in order to show the light. Maybe there's a happy little waterfall happening over here. Now we don't want him to get lonely, so we'll give him a little friend. That easy."));
}

var make = Index;

var $$default = Index;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
