// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Test(Props) {
  return React.createElement("div", undefined, "Goodbye Test");
}

var make = Test;

var $$default = Test;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
