// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link from "next/link";
import * as NavbarStyles$ReNext from "./NavbarStyles.bs.js";

function make(param) {
  return React.createElement("div", {
              className: "hero-head"
            }, React.createElement("nav", {
                  className: "navbar main-title",
                  id: "topnav"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: "navbar-brand"
                        }, React.createElement(Link.default, {
                              href: "/",
                              children: React.createElement("a", {
                                    className: NavbarStyles$ReNext.subtitle
                                  }, "Bracket Factory")
                            }), React.createElement("span", {
                              className: "navbar-burger burger"
                            }, React.createElement("span", undefined), React.createElement("span", undefined), React.createElement("span", undefined))), React.createElement("div", {
                          className: "navbar-menu",
                          id: "navbarMenu"
                        }, React.createElement("div", {
                              className: "navbar-end"
                            }, React.createElement("div", {
                                  className: "navbar-item"
                                }, React.createElement(Link.default, {
                                      href: "/about",
                                      children: React.createElement("a", undefined, "About")
                                    })), React.createElement("div", {
                                  className: "navbar-item"
                                }, React.createElement(Link.default, {
                                      href: "/about",
                                      children: React.createElement("a", undefined, "Contact")
                                    })))))));
}

export {
  make ,
  
}
/* react Not a pure module */
