// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Post$ReNext from "../layout/Post.bs.js";
import * as Section$ReNext from "./Section.bs.js";

function Posts(Props) {
  return React.createElement(Section$ReNext.make, {
              title: "BF Design",
              subtitle: "ReasonML Blog",
              children: React.createElement("div", {
                    className: "columns is-multiline"
                  }, React.createElement(Post$ReNext.make, { }), React.createElement(Post$ReNext.make, { }), React.createElement(Post$ReNext.make, { }), React.createElement(Post$ReNext.make, { }), React.createElement(Post$ReNext.make, { }))
            });
}

var make = Posts;

export {
  make ,
  
}
/* react Not a pure module */
